export const lists = [
    {
      id: "1",
      name: "Mai Phương Thúy",
      sbd: "1",
      born: "2000-05-27",
      email: "tamle2603.tn@gmail.com",
      sdt: "0983772898",
      img: "https://missworldvn.com/wp-content/uploads/2019/07/5Untitled-1.jpg",
      address: "Ung Van Khiem",
      jobs: "Design",
      nation: "Viet Nam",
      height: "176cm",
      weight: "45kg",
      education: "Đại Học",
      sbc: "1232",
    },
    {
      id: "2",
      name: "Lê Xuân Lan",
      sbd: "1394",
      born: "09-02-2000",
      email: "tamle2603.tn@gmail.com",
      sdt: "0906905827",
      img: "https://missworldvn.com/wp-content/uploads/2019/07/8Untitled-1.jpg",
      address: "Ung Van Khiem",
      jobs: "Design",
      nation: "Viet Nam",
      height: "176cm",
      weight: "45kg",
      education: "Đại Học",
      sbc: "1232",
    },
    {
      id: "3",
      name: "Đậu Hải Minh Anh",
      sbd: "1394",
      born: "09-02-2000",
      email: "tamle2603.tn@gmail.com",
      sdt: "0906905827",
      img: "https://missworldvn.com/wp-content/uploads/2019/07/34Untitled-1.jpg",
      address: "Ung Van Khiem",
      jobs: "Design",
      nation: "Viet Nam",
      height: "176cm",
      weight: "45kg",
      education: "Đại Học",
      sbc: "1232",
    },
    {
      id: "4",
      name: "Đậu Hải Minh Anh",
      sbd: "1394",
      born: "09-02-2000",
      email: "tamle2603.tn@gmail.com",
      sdt: "0906905827",
      img: "https://missworldvn.com/wp-content/uploads/2019/07/14Untitled-1.jpg",
      address: "Ung Van Khiem",
      jobs: "Design",
      nation: "Viet Nam",
      height: "176cm",
      weight: "45kg",
      education: "Đại Học",
      sbc: "1232",
    },
    {
      id: "5",
      name: "Đậu Hải Minh Anh",
      sbd: "1394",
      born: "09-02-2000",
      email: "tamle2603.tn@gmail.com",
      sdt: "0906905827",
      img: "https://missworldvn.com/wp-content/uploads/2019/07/28Untitled-1.jpg",
      address: "Ung Van Khiem",
      jobs: "Design",
      nation: "Viet Nam",
      height: "176cm",
      weight: "45kg",
      education: "Đại Học",
      sbc: "1232",
    },
    {
      id: "6",
      name: "Đậu Hải Minh Anh",
      sbd: "1394",
      born: "09-02-2000",
      email: "tamle2603.tn@gmail.com",
      sdt: "0906905827",
      img: "https://missworldvn.com/wp-content/uploads/2019/07/15Untitled-1.jpg",
      address: "Ung Van Khiem",
      jobs: "Design",
      nation: "Viet Nam",
      height: "176cm",
      weight: "45kg",
      education: "Đại Học",
      sbc: "1232",
    },
    {
      id: "7",
      name: "Đậu Hải Minh Anh",
      sbd: "1394",
      born: "09-02-2000",
      email: "tamle2603.tn@gmail.com",
      sdt: "0906905827",
      img: "https://missworldvn.com/wp-content/uploads/2019/07/37Untitled-1-Recovered.jpg",
      address: "Ung Van Khiem",
      jobs: "Design",
      nation: "Viet Nam",
      height: "176cm",
      weight: "45kg",
      education: "Đại Học",
      sbc: "1232",
    },
    {
      id: "8",
      name: "Đậu Hải Minh Anh",
      sbd: "1394",
      born: "09-02-2000",
      email: "tamle2603.tn@gmail.com",
      sdt: "0906905827",
      img: "https://missworldvn.com/wp-content/uploads/2019/07/17Untitled-1.jpg",
      address: "Ung Van Khiem",
      jobs: "Design",
      nation: "Viet Nam",
      height: "176cm",
      weight: "45kg",
      education: "Đại Học",
      sbc: "1232",
    },
    {
      id: "9",
      name: "Đậu Hải Minh Anh",
      sbd: "1394",
      born: "09-02-2000",
      email: "tamle2603.tn@gmail.com",
      sdt: "0906905827",
      img: "https://missworldvn.com/wp-content/uploads/2019/07/20Untitled-1.jpg",
      address: "Ung Van Khiem",
      jobs: "Design",
      nation: "Viet Nam",
      height: "176cm",
      weight: "45kg",
      education: "Đại Học",
      sbc: "1232",
    },
    {
      id: "10",
      name: "Nguyễn Như Quỳnh",
      sbd: "10",
      born: "2000-04-24",
      email: " quynhle@gmail.com",
      sdt: "0983734334",
      img: "https://missworldvn.com/wp-content/uploads/2019/07/32Untitled-1.jpg",
      address: "Vạn Kiếp, phường 3, Phú Nhuận",
      jobs: "du hoc sinh",
      nation: "Viet Nam",
      height: "176cm",
      weight: "45kg",
      education: "Đại Học",
      sbc: "1232",
    },
    {
      id: "11",
      name: "Nguyễn Như Quỳnh",
      sbd: "10",
      born: "2000-04-24",
      email: " quynhle@gmail.com",
      sdt: "0983734334",
      img: "https://missworldvn.com/wp-content/uploads/2019/07/33Untitled-1.jpg",
      address: "Vạn Kiếp, phường 3, Phú Nhuận",
      jobs: "du hoc sinh",
      nation: "Viet Nam",
      height: "176cm",
      weight: "45kg",
      education: "Đại Học",
      sbc: "1232",
    },
    {
      id: "12",
      name: "Nguyễn Như Quỳnh",
      sbd: "10",
      born: "2000-04-24",
      email: " quynhle@gmail.com",
      sdt: "0983734334",
      img: "https://missworldvn.com/wp-content/uploads/2019/07/525Untitled-1-Recovered.jpg",
      address: "Vạn Kiếp, phường 3, Phú Nhuận",
      jobs: "du hoc sinh",
      nation: "Viet Nam",
      height: "176cm",
      weight: "45kg",
      education: "Đại Học",
      sbc: "1232",
    },
    {
      id: "13",
      name: "Nguyễn Như Quỳnh",
      sbd: "10",
      born: "2000-04-24",
      email: " quynhle@gmail.com",
      sdt: "0983734334",
      img: "https://missworldvn.com/wp-content/uploads/2019/07/4Untitled-1.jpg",
      address: "Vạn Kiếp, phường 3, Phú Nhuận",
      jobs: "du hoc sinh",
      nation: "Viet Nam",
      height: "176cm",
      weight: "45kg",
      education: "Đại Học",
      sbc: "1232",
    },
    {
      id: "14",
      name: "Nguyễn Như Quỳnh",
      sbd: "10",
      born: "2000-04-24",
      email: " quynhle@gmail.com",
      sdt: "0983734334",
      img: "https://missworldvn.com/wp-content/uploads/2019/07/31Untitled-1.jpg",
      address: "Vạn Kiếp, phường 3, Phú Nhuận",
      jobs: "du hoc sinh",
      nation: "Viet Nam",
      height: "176cm",
      weight: "45kg",
      education: "Đại Học",
      sbc: "1232",
    },
    {
      id: "15",
      name: "Nguyễn Như Quỳnh",
      sbd: "10",
      born: "2000-04-24",
      email: " quynhle@gmail.com",
      sdt: "0983734334",
      img: "https://missworldvn.com/wp-content/uploads/2019/07/32Untitled-1.jpg",
      address: "Vạn Kiếp, phường 3, Phú Nhuận",
      jobs: "du hoc sinh",
      nation: "Viet Nam",
      height: "176cm",
      weight: "45kg",
      education: "Đại Học",
      sbc: "1232",
    },
    {
      id: "16",
      name: "Nguyễn Như Quỳnh",
      sbd: "10",
      born: "2000-04-24",
      email: " quynhle@gmail.com",
      sdt: "0983734334",
      img: "https://missworldvn.com/wp-content/uploads/2019/07/32Untitled-1.jpg",
      address: "Vạn Kiếp, phường 3, Phú Nhuận",
      jobs: "du hoc sinh",
      nation: "Viet Nam",
      height: "176cm",
      weight: "45kg",
      education: "Đại Học",
      sbc: "1232",
    },
    {
      id: "17",
      name: "Nguyễn Như Quỳnh",
      sbd: "10",
      born: "2000-04-24",
      email: " quynhle@gmail.com",
      sdt: "0983734334",
      img: "https://missworldvn.com/wp-content/uploads/2019/07/32Untitled-1.jpg",
      address: "Vạn Kiếp, phường 3, Phú Nhuận",
      jobs: "du hoc sinh",
      nation: "Viet Nam",
      height: "176cm",
      weight: "45kg",
      education: "Đại Học",
      sbc: "1232",
    },
    {
      id: "18",
      name: "Nguyễn Như Quỳnh",
      sbd: "10",
      born: "2000-04-24",
      email: " quynhle@gmail.com",
      sdt: "0983734334",
      img: "https://missworldvn.com/wp-content/uploads/2019/07/32Untitled-1.jpg",
      address: "Vạn Kiếp, phường 3, Phú Nhuận",
      jobs: "du hoc sinh",
      nation: "Viet Nam",
      height: "176cm",
      weight: "45kg",
      education: "Đại Học",
      sbc: "1232",
    },
    {
      id: "19",
      name: "Nguyễn Như Quỳnh",
      sbd: "10",
      born: "2000-04-24",
      email: " quynhle@gmail.com",
      sdt: "0983734334",
      img: "https://missworldvn.com/wp-content/uploads/2019/07/32Untitled-1.jpg",
      address: "Vạn Kiếp, phường 3, Phú Nhuận",
      jobs: "du hoc sinh",
      nation: "Viet Nam",
      height: "176cm",
      weight: "45kg",
      education: "Đại Học",
      sbc: "1232",
    },
    {
      id: "20",
      name: "Nguyễn Như Quỳnh",
      sbd: "10",
      born: "2000-04-24",
      email: " quynhle@gmail.com",
      sdt: "0983734334",
      img: "https://missworldvn.com/wp-content/uploads/2019/07/32Untitled-1.jpg",
      address: "Vạn Kiếp, phường 3, Phú Nhuận",
      jobs: "du hoc sinh",
      nation: "Viet Nam",
      height: "176cm",
      weight: "45kg",
      education: "Đại Học",
      sbc: "1232",
    },
  ];
  
  //du lieu quan ly thi sinh
  export const rows = [
    {
      id: 1,
      img: "https://hoahauvietnam.bvote.vn/images/AVA/345.jpg",
      name: "Vu hoang Yen",
      sbd: "1234",
      born: " tay ninh,cai mat nhu cai banh in",
      age: "27",
      height: "1,76m",
      weight: "50kg",
      jobs: "cô y tá",
    },
    {
      id: 2,
      img: "https://hoahauvietnam.bvote.vn/images/AVA/345.jpg",
      name: "Vu hoang Yen",
      sbd: "1234",
      born: " tay ninh,cai mat nhu cai banh in",
      age: "27",
      height: "1,76m",
      weight: "50kg",
      jobs: "cô y tá",
    },
    {
      id: 3,
      img: "https://hoahauvietnam.bvote.vn/images/AVA/345.jpg",
      name: "Vu hoang Yen",
      sbd: "1234",
      born: " tay ninh,cai mat nhu cai banh in",
      age: "27",
      height: "1,76m",
      weight: "50kg",
      jobs: "cô y tá",
    },
    {
      id: 4,
      img: "https://hoahauvietnam.bvote.vn/images/AVA/345.jpg",
      name: "Vu hoang Yen",
      sbd: "1234",
      born: " tay ninh,cai mat nhu cai banh in",
      age: "27",
      height: "1,76m",
      weight: "50kg",
      jobs: "cô y tá",
    },
    {
      id: 5,
      img: "https://hoahauvietnam.bvote.vn/images/AVA/345.jpg",
      name: "Vu hoang Yen",
      sbd: "1234",
      born: " tay ninh,cai mat nhu cai banh in",
      age: "27",
      height: "1,76m",
      weight: "50kg",
      jobs: "cô y tá",
    },
    {
      id: 6,
      img: "https://hoahauvietnam.bvote.vn/images/AVA/345.jpg",
      name: "Vu hoang Yen",
      sbd: "1234",
      born: " tay ninh,cai mat nhu cai banh in",
      age: "27",
      height: "1,76m",
      weight: "50kg",
      jobs: "cô y tá",
    },
  ];
  